apiVersion: v1
kind: ConfigMap
metadata:
  name: recruitment-app-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  # MONGO_URI: "mongodb://cm9vdAo=:cm9vdHBhc3N3b3JkCg==@mongo-service:27017/hr_system?authSource=admin"
  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitment-app
  template:
    metadata:
      labels:
        app: recruitment-app
    spec:
      containers:
      - name: recruitment-app
        image: praveenx03/recruitment:v1.1.0
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: recruitment-app-config
              key: PORT
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: recruitment-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recruitment-secret
              key: password
        - name: MONGO_URI
          value: "mongodb://$(MONGO_INIT_DB_ROOT_USERNAME):$(MONGO_INIT_DB_ROOT_PASSWORD)@mongo-service:27017/hr_system?authSource=admin"
        
---
apiVersion: v1
kind: Service
metadata:
  name: recruitment-app-service
spec:
  selector:
    app: recruitment-app
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort