version: '3.8'

services:
  recruitment-app: 
    image: praveenx03/recruitment:v1.1.0
    container_name: recruitment-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://rootuser:rootpassword@mongo:27017/hr_system?authSource=admin
    depends_on:
      - Database
    networks:
      - net1
  
  Database:
    image: mongo:7
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    networks:
      - net2
      - net1
    
      
networks:
  net1:
  net2:
