events {}

http{
    # stream {
    server{

#   upstream mongodb {
#       server mongo:27017;
#   }

#   server {
#       listen 27017;
#       proxy_pass mongodb;
#   }

        listen 80;
        location /api {
            proxy_pass http://recruitment-app:3000;
        }
    }
}